"use client";

import { useState } from "react";
import { Conversation } from "./AssistantHome";
import {
  Share2,
  Copy,
  Link as LinkIcon,
  Download,
  Mail,
  MessageSquare,
  X,
  Check,
  FileText,
} from "lucide-react";

interface ShareModalProps {
  conversation: Conversation | null;
  isOpen: boolean;
  onClose: () => void;
  onShowToast: (msg: string) => void;
}

export function ShareModal({
  conversation,
  isOpen,
  onClose,
  onShowToast,
}: ShareModalProps) {
  const [copiedType, setCopiedType] = useState<"link" | "markdown" | "text" | null>(null);

  if (!isOpen || !conversation) return null;

  const chatTitle = conversation.title || "ubix Mentorship Chat";
  const messages = conversation.messages || [];

  // Generate clean Markdown transcript
  const getMarkdownTranscript = () => {
    let md = `# ${chatTitle}\n*Generated by ubix Assistant on ${new Date().toLocaleDateString()}*\n\n---\n\n`;
    messages.forEach((m) => {
      const sender = m.role === "user" ? "**User**" : `**ubix Assistant** (${m.engine || "AI Mentor"})`;
      const time = m.time ? ` *[${m.time}]*` : "";
      md += `### ${sender}${time}\n\n${m.text}\n\n`;
      if (m.attachedDocName) {
        md += `> *Attached File: ${m.attachedDocName}*\n\n`;
      }
      if (m.intent?.featureTitle) {
        md += `> *Interactive Tool: ${m.intent.featureTitle}*\n\n`;
      }
    });
    return md;
  };

  // Generate plain text transcript
  const getPlainTextTranscript = () => {
    let txt = `=== ${chatTitle} ===\nubix Mentorship\nDate: ${new Date().toLocaleString()}\n\n`;
    messages.forEach((m) => {
      const sender = m.role === "user" ? "User" : "ubix Assistant";
      txt += `[${m.time || ""}] ${sender}:\n${m.text}\n\n`;
    });
    return txt;
  };

  // 1. Native Web Share API
  const handleNativeShare = async () => {
    if (typeof navigator !== "undefined" && navigator.share) {
      try {
        const preview =
          messages
            .filter((m) => m.role === "assistant")
            .map((m) => m.text)
            .slice(-1)[0] || "Career advice from ubix Assistant";

        await navigator.share({
          title: chatTitle,
          text: `ubix Assistant Mentorship Session: "${chatTitle}"\n\nLatest takeaway: ${preview.slice(0, 160)}...`,
          url: window.location.href,
        });
        onShowToast("Shared successfully!");
      } catch (err: any) {
        if (err.name !== "AbortError") {
          console.error("Web share failed", err);
        }
      }
    } else {
      copyLink();
    }
  };

  // 2. Copy Link
  const copyLink = async () => {
    try {
      if (typeof navigator !== "undefined" && navigator.clipboard) {
        await navigator.clipboard.writeText(window.location.href);
        setCopiedType("link");
        onShowToast("Link copied to clipboard!");
        setTimeout(() => setCopiedType(null), 2500);
      }
    } catch {
      onShowToast("Failed to copy link");
    }
  };

  // 3. Copy Markdown
  const copyMarkdown = async () => {
    try {
      if (typeof navigator !== "undefined" && navigator.clipboard) {
        await navigator.clipboard.writeText(getMarkdownTranscript());
        setCopiedType("markdown");
        onShowToast("Markdown formatted conversation copied!");
        setTimeout(() => setCopiedType(null), 2500);
      }
    } catch {
      onShowToast("Failed to copy markdown");
    }
  };

  // 4. Download Markdown File
  const downloadMarkdown = () => {
    const element = document.createElement("a");
    const file = new Blob([getMarkdownTranscript()], { type: "text/markdown;charset=utf-8" });
    element.href = URL.createObjectURL(file);
    element.download = `${chatTitle.toLowerCase().replace(/[^a-z0-9]+/g, "-")}.md`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
    onShowToast("Downloaded Markdown file!");
  };

  // 5. Download Plain Text
  const downloadPlainText = () => {
    const element = document.createElement("a");
    const file = new Blob([getPlainTextTranscript()], { type: "text/plain;charset=utf-8" });
    element.href = URL.createObjectURL(file);
    element.download = `${chatTitle.toLowerCase().replace(/[^a-z0-9]+/g, "-")}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
    onShowToast("Downloaded Text transcript!");
  };

  // WhatsApp Share Link
  const getWhatsAppShareUrl = () => {
    const shareText = `ubix Mentorship Chat: ${chatTitle}\n${typeof window !== "undefined" ? window.location.href : ""}`;
    return `https://api.whatsapp.com/send?text=${encodeURIComponent(shareText)}`;
  };

  // LinkedIn Share Link
  const getLinkedInShareUrl = () => {
    return `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(typeof window !== "undefined" ? window.location.href : "")}`;
  };

  // Email Share Link
  const getEmailShareUrl = () => {
    const subject = encodeURIComponent(`ubix Mentorship: ${chatTitle}`);
    const body = encodeURIComponent(`Here is my ubix chat transcript:\n\n${getPlainTextTranscript()}`);
    return `mailto:?subject=${subject}&body=${body}`;
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 backdrop-blur-md p-4 animate-in fade-in duration-150">
      <div
        className="w-full max-w-lg rounded-2xl border border-white/[0.08] bg-surface-elevated p-6 shadow-2xl space-y-5 animate-in zoom-in-95 duration-150"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between border-b border-white/[0.08] pb-3.5">
          <div className="flex items-center gap-2.5">
            <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-accent/15 border border-accent/30 text-accent shadow-xs">
              <Share2 className="w-4 h-4" />
            </div>
            <div>
              <h2 className="text-sm font-bold text-ink">Share Conversation</h2>
              <p className="text-[11px] text-ink/50 truncate max-w-[280px]">{chatTitle}</p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="rounded-lg p-1.5 text-ink/50 hover:bg-white/[0.06] hover:text-ink transition-colors flex items-center justify-center"
            title="Close modal"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Chat Stats Preview */}
        <div className="rounded-xl border border-white/[0.06] bg-surface p-3.5 text-xs text-ink/75 space-y-1.5">
          <div className="flex items-center justify-between font-semibold text-ink">
            <span>{messages.length} messages in discussion</span>
            <span className="text-[11px] text-ink/40 font-mono">
              {new Date(conversation.updatedAt).toLocaleDateString()}
            </span>
          </div>
          <p className="text-[11px] text-ink/60 line-clamp-2">
            {messages[messages.length - 1]?.text || "No messages yet"}
          </p>
        </div>

        {/* Quick Action Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
          {/* Copy Markdown */}
          <button
            type="button"
            onClick={copyMarkdown}
            className="flex items-center justify-center gap-2 rounded-xl border border-white/[0.08] bg-white/[0.03] py-2.5 px-3 text-xs font-semibold text-ink hover:border-accent/40 hover:bg-white/[0.06] hover:text-accent transition-all cursor-pointer"
          >
            {copiedType === "markdown" ? (
              <Check className="w-3.5 h-3.5 text-success" />
            ) : (
              <Copy className="w-3.5 h-3.5 text-ink/60" />
            )}
            <span>{copiedType === "markdown" ? "Copied Markdown" : "Copy Markdown"}</span>
          </button>

          {/* Copy Page Link */}
          <button
            type="button"
            onClick={copyLink}
            className="flex items-center justify-center gap-2 rounded-xl border border-white/[0.08] bg-white/[0.03] py-2.5 px-3 text-xs font-semibold text-ink hover:border-accent/40 hover:bg-white/[0.06] hover:text-accent transition-all cursor-pointer"
          >
            {copiedType === "link" ? (
              <Check className="w-3.5 h-3.5 text-success" />
            ) : (
              <LinkIcon className="w-3.5 h-3.5 text-ink/60" />
            )}
            <span>{copiedType === "link" ? "Link Copied" : "Copy Link"}</span>
          </button>

          {/* Download Markdown */}
          <button
            type="button"
            onClick={downloadMarkdown}
            className="flex items-center justify-center gap-2 rounded-xl border border-white/[0.08] bg-white/[0.03] py-2.5 px-3 text-xs font-semibold text-ink hover:border-accent/40 hover:bg-white/[0.06] hover:text-accent transition-all cursor-pointer"
          >
            <Download className="w-3.5 h-3.5 text-ink/60" />
            <span>Download .MD</span>
          </button>

          {/* Download Text */}
          <button
            type="button"
            onClick={downloadPlainText}
            className="flex items-center justify-center gap-2 rounded-xl border border-white/[0.08] bg-white/[0.03] py-2.5 px-3 text-xs font-semibold text-ink hover:border-accent/40 hover:bg-white/[0.06] hover:text-accent transition-all cursor-pointer"
          >
            <FileText className="w-3.5 h-3.5 text-ink/60" />
            <span>Download .TXT</span>
          </button>
        </div>

        {/* Direct Channels */}
        <div className="space-y-2 pt-2 border-t border-white/[0.08]">
          <p className="text-[11px] font-bold uppercase tracking-wider text-ink/40">Share Directly</p>
          <div className="flex flex-wrap items-center gap-2">
            {/* Native Mobile Share if available */}
            {typeof navigator !== "undefined" && "share" in navigator && (
              <button
                type="button"
                onClick={handleNativeShare}
                className="flex items-center gap-1.5 rounded-lg border border-accent/40 bg-accent/15 px-3 py-1.5 text-xs font-medium text-accent hover:bg-accent/25 transition-colors cursor-pointer"
              >
                <Share2 className="w-3.5 h-3.5" />
                <span>Device Share</span>
              </button>
            )}

            {/* WhatsApp */}
            <a
              href={getWhatsAppShareUrl()}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-1.5 rounded-lg border border-white/[0.08] bg-white/[0.03] px-3 py-1.5 text-xs font-medium text-ink/80 hover:text-success hover:border-success/40 transition-colors"
            >
              <MessageSquare className="w-3.5 h-3.5" />
              <span>WhatsApp</span>
            </a>

            {/* LinkedIn */}
            <a
              href={getLinkedInShareUrl()}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-1.5 rounded-lg border border-white/[0.08] bg-white/[0.03] px-3 py-1.5 text-xs font-medium text-ink/80 hover:text-info hover:border-info/40 transition-colors"
            >
              <Share2 className="w-3.5 h-3.5" />
              <span>LinkedIn</span>
            </a>

            {/* Email */}
            <a
              href={getEmailShareUrl()}
              className="flex items-center gap-1.5 rounded-lg border border-white/[0.08] bg-white/[0.03] px-3 py-1.5 text-xs font-medium text-ink/80 hover:text-accent hover:border-accent/40 transition-colors"
            >
              <Mail className="w-3.5 h-3.5" />
              <span>Email</span>
            </a>
          </div>
        </div>

        {/* Footer Close */}
        <div className="flex justify-end pt-2">
          <button
            type="button"
            onClick={onClose}
            className="rounded-xl border border-white/[0.08] bg-white/[0.04] px-4 py-2 text-xs font-semibold text-ink hover:bg-white/[0.08] transition-colors cursor-pointer"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}
