import { z } from "zod";
import type { FeatureId, ResumeTab } from "@/lib/intent";

export const ALLOWED_FEATURES = ["resume", "roadmap", "courses", "practice", "local"] as const;
export const ALLOWED_RESUME_TABS = ["analyzer", "personalizer", "builder"] as const;

export const AllowedFeatureSchema = z.enum(ALLOWED_FEATURES);
export const AllowedResumeTabSchema = z.enum(ALLOWED_RESUME_TABS);

/**
 * Strict check for valid internal feature IDs.
 */
export function isAllowedFeature(val: unknown): val is FeatureId {
  return typeof val === "string" && (ALLOWED_FEATURES as readonly string[]).includes(val);
}

/**
 * Strict check for valid resume tabs.
 */
export function isAllowedResumeTab(val: unknown): val is ResumeTab {
  return typeof val === "string" && (ALLOWED_RESUME_TABS as readonly string[]).includes(val);
}

/**
 * Validates and sanitizes navigation paths generated by AI or tool calls.
 * Strictly forbids external URLs, JavaScript URIs, protocol-relative links,
 * and paths outside the verified internal feature registry.
 */
export function sanitizeNavigation(
  rawPath: unknown,
  rawTab?: unknown
): { feature: FeatureId; resumeTab?: ResumeTab } | null {
  if (typeof rawPath !== "string") return null;

  const trimmed = rawPath.trim().toLowerCase();

  // Explicitly reject dangerous schemes, external links, and path traversal
  if (
    trimmed.startsWith("http:") ||
    trimmed.startsWith("https:") ||
    trimmed.startsWith("//") ||
    trimmed.startsWith("javascript:") ||
    trimmed.startsWith("data:") ||
    trimmed.startsWith("vbscript:") ||
    trimmed.includes("..")
  ) {
    console.warn(`[Security] Blocked unauthorized navigation target: ${trimmed}`);
    return null;
  }

  // Parse valid internal feature
  let targetFeature: FeatureId | null = null;
  let targetTab: ResumeTab | undefined = undefined;

  if (trimmed === "resume" || trimmed.includes("resume") || trimmed.includes("builder") || trimmed.includes("cv")) {
    targetFeature = "resume";
    if (trimmed.includes("builder")) {
      targetTab = "builder";
    } else if (trimmed.includes("personalizer") || trimmed.includes("tailor")) {
      targetTab = "personalizer";
    } else {
      targetTab = "analyzer";
    }
  } else if (trimmed === "roadmap" || trimmed.includes("roadmap") || trimmed.includes("career")) {
    targetFeature = "roadmap";
  } else if (
    trimmed === "courses" ||
    trimmed.includes("course") ||
    trimmed.includes("audiobook") ||
    trimmed.includes("learn")
  ) {
    targetFeature = "courses";
  } else if (
    trimmed === "practice" ||
    trimmed.includes("practice") ||
    trimmed.includes("assessment") ||
    trimmed.includes("interview")
  ) {
    targetFeature = "practice";
  } else if (
    trimmed === "local" ||
    trimmed.includes("job") ||
    trimmed.includes("internship") ||
    trimmed.includes("local")
  ) {
    targetFeature = "local";
  }

  if (!targetFeature || !isAllowedFeature(targetFeature)) {
    return null;
  }

  if (rawTab && isAllowedResumeTab(rawTab)) {
    targetTab = rawTab;
  }

  return { feature: targetFeature, resumeTab: targetTab };
}

// ─── Zod Schemas for AI Output & Tool Call Validation ─────────────────────────

export const AccessibilityPreferencesUpdateSchema = z.object({
  interactionMode: z.enum(["voice", "tactile", "visual", "keyboard", "deaf_assisted"]).optional(),
  speechOutput: z.boolean().optional(),
  screenReaderOptimized: z.boolean().optional(),
  highContrast: z.boolean().optional(),
  largeText: z.boolean().optional(),
  fontSize: z.number().min(10).max(36).optional(),
  audioDescriptions: z.boolean().optional(),
  captionsEnabled: z.boolean().optional(),
  hapticFeedback: z.boolean().optional(),
}).strict();

export const UserProfileUpdateSchema = z.object({
  name: z.string().max(100).optional(),
  email: z.string().email().max(255).optional(),
  targetRole: z.string().max(100).optional(),
  skills: z.array(z.string().max(50)).max(50).optional(),
  experienceLevel: z.string().max(50).optional(),
}).strict();

export const AudiobookControlSchema = z.object({
  action: z.enum(["play", "pause", "seek", "stop"]),
  seconds: z.number().min(-3600).max(3600).optional(),
}).strict();

export const DoubtSolvedLockSchema = z.object({
  topic: z.string().max(200).optional(),
  solved: z.boolean().optional(),
}).strict();

export const NavigateToSchema = z.object({
  path: z.string().max(200),
  tab: z.string().max(50).optional(),
}).strict();

export const AiToolCallSchema = z.discriminatedUnion("tool", [
  z.object({
    tool: z.literal("updateAccessibilityPreferences"),
    parameters: AccessibilityPreferencesUpdateSchema,
  }),
  z.object({
    tool: z.literal("updateUserProfile"),
    parameters: UserProfileUpdateSchema,
  }),
  z.object({
    tool: z.literal("audiobookControl"),
    action: z.enum(["play", "pause", "seek", "stop"]),
    seconds: z.number().min(-3600).max(3600).optional(),
  }),
  z.object({
    tool: z.literal("doubtSolvedContextLock"),
    parameters: DoubtSolvedLockSchema.optional(),
  }),
  z.object({
    tool: z.literal("navigateTo"),
    parameters: NavigateToSchema,
  }),
]);

export const AiChatResponseSchema = z.object({
  reply: z.string().max(50000),
  feature: AllowedFeatureSchema.nullable().optional(),
  resumeTab: AllowedResumeTabSchema.optional(),
  toolCall: z.any().optional(),
});

export type ValidatedAiToolCall = z.infer<typeof AiToolCallSchema>;
export type ValidatedAiChatResponse = z.infer<typeof AiChatResponseSchema>;

/**
 * Strips HTML, SVG, script tags, event handlers, and dangerous schemes from user inputs
 * to prevent XSS in resume parsing and preview rendering.
 */
export function sanitizeHtmlAndSvg(input: string): string {
  if (!input || typeof input !== "string") return "";
  return input
    .replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, "")
    .replace(/<svg\b[^<]*(?:(?!<\/svg>)<[^<]*)*<\/svg>/gi, "")
    .replace(/<iframe\b[^<]*(?:(?!<\/iframe>)<[^<]*)*<\/iframe>/gi, "")
    .replace(/<object\b[^<]*(?:(?!<\/object>)<[^<]*)*<\/object>/gi, "")
    .replace(/<embed\b[^<]*(?:(?!<\/embed>)<[^<]*)*<\/embed>/gi, "")
    .replace(/on\w+\s*=\s*(["'][^"']*["']|[^\s>]+)/gi, "")
    .replace(/javascript:/gi, "")
    .replace(/data:text\/html/gi, "")
    .replace(/<[^>]+>/g, "");
}

/**
 * Validates and sanitizes URLs ensuring they only use safe protocols (http, https, mailto, tel).
 */
export function sanitizeSafeUrl(rawUrl: string): string {
  if (!rawUrl || typeof rawUrl !== "string") return "";
  const trimmed = rawUrl.trim();
  if (
    trimmed.toLowerCase().startsWith("javascript:") ||
    trimmed.toLowerCase().startsWith("data:") ||
    trimmed.toLowerCase().startsWith("vbscript:")
  ) {
    return "#";
  }
  return trimmed;
}
